#!/bin/sh
sudo sh -c 'echo "# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)" > /etc/resolv.conf'
sudo sh -c 'echo "#      DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN" >> /etc/resolv.conf'
sudo sh -c 'echo "nameserver 10.162.228.210" >> /etc/resolv.conf'
sudo sh -c 'echo "nameserver 10.20.64.11" >> /etc/resolv.conf'
sudo sh -c 'echo "nameserver 10.28.64.11" >> /etc/resolv.conf'
sudo sh -c 'echo "search edm.com emrsn.com" >> /etc/resolv.conf'
